### ISSUE TITLE
Android Basics: Introduction to Coroutines in Android Studio

### ISSUE THREAD

**Issue by AreyouShura** [google-developer-training/basic-android-kotlin-compose-training-race-tracker#4]
Can't download the starter code.
 NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by osuleymanova** [comment]
Hi @AreyouShura,

Could you be more specific with the issue you are facing? If it's possible, please provide the steps of getting the starter code and the screenshot of the error.

**Comment by AreyouShura** [comment]
Судя по нику вы и на русском понимаете?
просто жму на зеленую кнопку "скачать" и хром выдает ошибку, которую я выше указал. не позволяет перейти на страницу для скачивания из за ошибки в сертификатах.

**Comment by osuleymanova** [comment]
Здравствуйте, @AreyouShura 
Это верно, я понимаю по-русски. Давайте вернемся к устранению вашей проблемы.
Существуют различные варианты загрузки кода из репозитория GitHub:
1. Нажмите кнопку "Загрузить zip", затем откройте и распакуйте его в Finder:

![Screen Shot 2022-11-22 at 5 07 20 PM](https://user-images.githubusercontent.com/86437155/203453658-8c0f1f2c-e3e2-4aa5-81ee-541f60a9d44c.png)

 В вашем случае вы получили сообщение об ошибке (NET::ERR_CERT_COMMON_NAME_INVALID). Пользователи, которые видят этот экран, могут попробовать перейти на сайт по протоколу HTTP.
Самая основная причина ошибки NET::ERR_CERT_COMMON_NAME_INVALID заключается в том, что домен вашего сайта не соответствует общему имени, указанному в вашем SSL-сертификате. Итак, первое исправление, которое вы можете попробовать, - это просмотреть свой сертификат, чтобы определить, не был ли он неправильно настроен.
Если это не решит проблему, пожалуйста, введите NET::ERR_CERT_COMMON_NAME_INVALID в поле поиска Google, и вы обязательно найдете подходящее решение.
2. Или вы можете клонировать репозиторий GitHub, как описано в codelab, введя команды git в терминале:

![Screen Shot 2022-11-22 at 5 38 31 PM](https://user-images.githubusercontent.com/86437155/203453963-135c2830-b72b-4246-80bd-cfc2b4abe546.png)

Пожалуйста, дайте нам знать, если после этого вы все еще столкнетесь с проблемой загрузки кода.

Hello, @AreyouShura 
There are different variants to download the code from the GitHub repository:
1. You can click the button "Download zip", then open and unzip it in Finder.
In your case you've got the error message (NET::ERR_CERT_COMMON_NAME_INVALID) listed below the main message. 
The most basic cause of the NET::ERR_CERT_COMMON_NAME_INVALID error is that your site’s domain doesn’t match the common name listed on your SSL certificate. So, the first fix you’ll want to try is viewing your certificate to determine if it’s been misconfigured. Users who see this screen may also choose to proceed to the site anyway using HTTP.  If it doesn't resolve the problem, please enter NET::ERR_CERT_COMMON_NAME_INVALID in Google search field and you will definitely find the appropriate solution.
2. Or you can clone the GitHub repository as described in the codelab by entering the git commands in Terminal.

Please let us know if after that you still facing the issue of downloading the code.
