### ISSUE TITLE
Android Basics: Introduction to Coroutines in Kotlin Playground

### ISSUE THREAD

**Issue by NeutrinoWS** [google-developer-training/basic-android-kotlin-compose-training-race-tracker#5]
Hello, 
Hello. I found an error in the 2nd paragraph in the code area.
![image](https://user-images.githubusercontent.com/14983026/204086779-72985636-ea0b-4985-b73f-619b79de0c72.png)
![image](https://user-images.githubusercontent.com/14983026/204086790-4b0aea51-b923-454e-9c20-b032c74cfd3c.png)

**Comment by osuleymanova** [comment]
Hello @NeutrinoWS,

The codelab content and the code snippets were updated, please refer to the link below:
https://developer.android.com/codelabs/basic-android-kotlin-compose-coroutines-kotlin-playground#3
