### ISSUE TITLE
Android Basics: Introduction to Coroutines in Android Studio

### ISSUE THREAD

**Issue by hassan0599** [google-developer-training/basic-android-kotlin-compose-training-race-tracker#6]
Task 4 (Start the race):
Step 1 should read:
"Open the `RaceTrackerApp.kt` file located in the `com.example.racetracker.ui` package." instead of 
"Open to the `RaceTrackerApp.kt` file located in the `com.example.racetracker.ui` package."

**Comment by osuleymanova** [comment]
Hello @hassan0599,

Thank you for reaching out to us and reporting tis typo. It is fixed and will be published soon.
